apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-hello-world-app
  template:
    metadata:
      labels:
        app: eks-hello-world-app
    spec:
      containers:
      - name: eks-hello-world-app
        image: <your-docker-image>
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: eks-hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: eks-hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
