name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t ${{ vars.Account_ID }}.dkr.ecr.us-east-1.amazonaws.com/hello-world-js:${{ github.run_number }} ./app

      - name: Push Docker image to ECR
        run: docker push ${{ vars.Account_ID }}.dkr.ecr.us-east-1.amazonaws.com/hello-world-js:${{ github.run_number }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name demo-project_dev

      - name: Deploy with Helm
        run: |
          helm upgrade --install hello-world-js ./app/helm-chart \
            --set image.repository=${{ vars.Account_ID }}.dkr.ecr.us-east-1.amazonaws.com/hello-world-js \
            --set image.tag=${{ github.run_number }} \
            --values ./app/helm-chart/values-dev.yaml
